import os

import psycopg2

from api.db.connection import connect_db, get_database_url
from api.services.app_settings import bootstrap_settings_from_env, ensure_settings_schema, sync_setting_descriptions

CANONICAL_FEEDBACK_VALUES = (
    "interested",
    "never_watch",
    "watched_like",
    "watched_dislike",
)


def apply_schema_updates(conn) -> None:
    with conn.cursor() as cur:
        ensure_settings_schema(conn)
        sync_setting_descriptions(conn)
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.users
            ADD COLUMN IF NOT EXISTS friendly_name text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.users
            ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.users
            ADD COLUMN IF NOT EXISTS modified_at timestamp with time zone NOT NULL DEFAULT now()
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.feedback_reason (
                code text PRIMARY KEY,
                label text NOT NULL,
                applies_to text NOT NULL,
                suppress_default boolean NOT NULL DEFAULT false
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.user_feedback (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username text NOT NULL,
                rating_key integer NOT NULL,
                feedback text NOT NULL,
                reason_code text REFERENCES public.feedback_reason(code),
                suppress boolean DEFAULT false,
                created_at timestamp without time zone DEFAULT now(),
                source text DEFAULT 'ui'
            )
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD COLUMN IF NOT EXISTS plex_watchlist_status text NOT NULL DEFAULT 'not_applicable'
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD COLUMN IF NOT EXISTS plex_watchlist_synced_at timestamp without time zone
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD COLUMN IF NOT EXISTS modified_at timestamp without time zone NOT NULL DEFAULT now()
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS label_source text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS feedback_value text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS engagement_type text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS watch_count integer
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS max_single_session_seconds integer
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS total_played_seconds integer
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_training_data_user_media
            ON public.training_data (username, rating_key)
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.library
            ADD COLUMN IF NOT EXISTS plex_guid text
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_library_plex_guid
            ON public.library (plex_guid)
            """
        )
        cur.execute(
            """
            DO $$
            BEGIN
                IF to_regclass('public.watch_history') IS NOT NULL THEN
                    WITH ranked AS (
                        SELECT
                            ctid,
                            ROW_NUMBER() OVER (
                                PARTITION BY watch_id
                                ORDER BY watched_at DESC NULLS LAST, ctid DESC
                            ) AS rn
                        FROM public.watch_history
                    )
                    DELETE FROM public.watch_history wh
                    USING ranked
                    WHERE wh.ctid = ranked.ctid
                      AND ranked.rn > 1;

                    EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS watch_history_watch_id_uidx ON public.watch_history (watch_id)';
                END IF;
            END $$;
            """
        )
        cur.execute(
            """
            DO $$
            BEGIN
                IF to_regclass('public.watch_embeddings') IS NOT NULL THEN
                    DELETE FROM public.watch_embeddings
                    WHERE watch_id IS NULL
                       OR watch_id::text !~ '^[0-9]+$';

                    WITH ranked AS (
                        SELECT
                            ctid,
                            ROW_NUMBER() OVER (
                                PARTITION BY watch_id::integer
                                ORDER BY ctid DESC
                            ) AS rn
                        FROM public.watch_embeddings
                        WHERE watch_id::text ~ '^[0-9]+$'
                    )
                    DELETE FROM public.watch_embeddings we
                    USING ranked
                    WHERE we.ctid = ranked.ctid
                      AND ranked.rn > 1;

                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = 'watch_embeddings'
                          AND column_name = 'watch_id'
                          AND udt_name <> 'int4'
                    ) THEN
                        EXECUTE 'DROP INDEX IF EXISTS public.watch_embeddings_watch_id_uidx';
                        EXECUTE 'ALTER TABLE public.watch_embeddings ALTER COLUMN watch_id TYPE integer USING watch_id::integer';
                    END IF;

                    EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS watch_embeddings_watch_id_uidx ON public.watch_embeddings (watch_id)';
                END IF;
            END $$;
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            DROP CONSTRAINT IF EXISTS user_feedback_feedback_check
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.feedback_reason
            DROP CONSTRAINT IF EXISTS feedback_reason_applies_to_check
            """
        )
        cur.execute(
            """
            UPDATE public.feedback_reason
            SET
                applies_to = CASE
                    WHEN code = 'thumb_up' THEN 'watched_like'
                    WHEN code = 'thumb_down' THEN 'never_watch'
                    ELSE applies_to
                END,
                suppress_default = CASE
                    WHEN code = 'thumb_up' THEN TRUE
                    WHEN code = 'thumb_down' THEN TRUE
                    ELSE suppress_default
                END
            WHERE code IN ('thumb_up', 'thumb_down')
            """
        )
        cur.execute(
            """
            INSERT INTO public.feedback_reason (code, label, applies_to, suppress_default)
            VALUES
                ('interested', 'Want to watch', 'interested', FALSE),
                ('never_watch', 'Never watch', 'never_watch', TRUE),
                ('watched_like', 'Watched, liked', 'watched_like', TRUE),
                ('watched_dislike', 'Watched, disliked', 'watched_dislike', TRUE)
            ON CONFLICT (code) DO UPDATE SET
                label = EXCLUDED.label,
                applies_to = EXCLUDED.applies_to,
                suppress_default = EXCLUDED.suppress_default
            """
        )

        cur.execute(
            """
            UPDATE public.user_feedback
            SET
                feedback = CASE
                    WHEN feedback = 'up' THEN 'watched_like'
                    WHEN feedback = 'down' THEN 'never_watch'
                    ELSE feedback
                END,
                reason_code = CASE
                    WHEN reason_code = 'thumb_up' THEN 'watched_like'
                    WHEN reason_code = 'thumb_down' THEN 'never_watch'
                    ELSE reason_code
                END,
                suppress = CASE
                    WHEN feedback = 'up' THEN TRUE
                    WHEN feedback = 'down' THEN TRUE
                    ELSE suppress
                END,
                plex_watchlist_status = CASE
                    WHEN feedback = 'up'
                        THEN 'not_applicable'
                    ELSE COALESCE(plex_watchlist_status, 'not_applicable')
                END,
                modified_at = COALESCE(modified_at, created_at, now())
            WHERE
                feedback IN ('up', 'down')
                OR reason_code IN ('thumb_up', 'thumb_down')
            """
        )
        cur.execute(
            """
            UPDATE public.user_feedback
            SET
                suppress = FALSE,
                plex_watchlist_status = CASE
                    WHEN feedback = 'interested'
                         AND COALESCE(plex_watchlist_status, '') IN ('', 'not_applicable')
                        THEN 'unresolved'
                    ELSE COALESCE(plex_watchlist_status, 'not_applicable')
                END,
                modified_at = COALESCE(modified_at, created_at, now())
            WHERE feedback = 'interested'
              AND suppress IS DISTINCT FROM FALSE
            """
        )

        cur.execute(
            """
            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY username, rating_key
                        ORDER BY COALESCE(modified_at, created_at, now()) DESC, id DESC
                    ) AS rn
                FROM public.user_feedback
            )
            DELETE FROM public.user_feedback uf
            USING ranked
            WHERE uf.id = ranked.id
              AND ranked.rn > 1
            """
        )

        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD CONSTRAINT user_feedback_feedback_check
            CHECK (
                feedback = ANY (
                    ARRAY[
                        'interested'::text,
                        'never_watch'::text,
                        'watched_like'::text,
                        'watched_dislike'::text
                    ]
                )
            )
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.feedback_reason
            ADD CONSTRAINT feedback_reason_applies_to_check
            CHECK (
                applies_to = ANY (
                    ARRAY[
                        'interested'::text,
                        'never_watch'::text,
                        'watched_like'::text,
                        'watched_dislike'::text
                    ]
                )
            )
            """
        )
        cur.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_user_feedback_username_rating_key
            ON public.user_feedback (username, rating_key)
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.user_email_preferences (
                user_id integer PRIMARY KEY REFERENCES public.users(user_id) ON DELETE CASCADE,
                digest_enabled boolean NOT NULL DEFAULT true,
                unsubscribe_token text NOT NULL UNIQUE,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                updated_at timestamp with time zone NOT NULL DEFAULT now()
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.email_digest_content (
                content_id integer PRIMARY KEY,
                message_html text NOT NULL DEFAULT '',
                updated_at timestamp with time zone NOT NULL DEFAULT now(),
                updated_by text
            )
            """
        )
        cur.execute(
            """
            INSERT INTO public.email_digest_content (content_id, message_html)
            VALUES (1, '')
            ON CONFLICT (content_id) DO NOTHING
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.email_digest_runs (
                run_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                delivery_type text NOT NULL,
                schedule_key text UNIQUE,
                triggered_by text,
                sample_username text,
                subject text,
                status text NOT NULL DEFAULT 'started',
                recipient_count integer NOT NULL DEFAULT 0,
                success_count integer NOT NULL DEFAULT 0,
                failure_count integer NOT NULL DEFAULT 0,
                notes text,
                started_at timestamp with time zone NOT NULL DEFAULT now(),
                completed_at timestamp with time zone
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.email_digest_deliveries (
                delivery_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_id integer NOT NULL REFERENCES public.email_digest_runs(run_id) ON DELETE CASCADE,
                delivery_type text NOT NULL,
                recipient_username text,
                recipient_email text NOT NULL,
                rendered_for_username text,
                status text NOT NULL,
                error_message text,
                sent_at timestamp with time zone NOT NULL DEFAULT now()
            )
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_email_digest_deliveries_run_id
            ON public.email_digest_deliveries (run_id)
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_email_digest_deliveries_rendered_for_username
            ON public.email_digest_deliveries (rendered_for_username)
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.pipeline_runs (
                run_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                delivery_type text NOT NULL,
                schedule_key text,
                triggered_by text,
                status text NOT NULL DEFAULT 'started',
                notes text,
                cancel_requested_at timestamp with time zone,
                cancel_requested_by text,
                last_heartbeat_at timestamp with time zone,
                current_stage_key text,
                current_pid integer,
                started_at timestamp with time zone NOT NULL DEFAULT now(),
                completed_at timestamp with time zone
            )
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.pipeline_runs
            ADD COLUMN IF NOT EXISTS cancel_requested_at timestamp with time zone
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.pipeline_runs
            ADD COLUMN IF NOT EXISTS cancel_requested_by text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.pipeline_runs
            ADD COLUMN IF NOT EXISTS last_heartbeat_at timestamp with time zone
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.pipeline_runs
            ADD COLUMN IF NOT EXISTS current_stage_key text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.pipeline_runs
            ADD COLUMN IF NOT EXISTS current_pid integer
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_pipeline_runs_started_at
            ON public.pipeline_runs (started_at DESC)
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_pipeline_runs_schedule_key
            ON public.pipeline_runs (schedule_key)
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.pipeline_run_stages (
                stage_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_id integer NOT NULL REFERENCES public.pipeline_runs(run_id) ON DELETE CASCADE,
                stage_key text NOT NULL,
                status text NOT NULL DEFAULT 'started',
                exit_code integer,
                stdout_tail text,
                stderr_tail text,
                started_at timestamp with time zone NOT NULL DEFAULT now(),
                completed_at timestamp with time zone
            )
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_pipeline_run_stages_run_id
            ON public.pipeline_run_stages (run_id)
            """
        )
    conn.commit()
    bootstrap_settings_from_env(conn)


def ensure_app_schema(db_url: str | None = None) -> None:
    resolved_db_url = db_url or get_database_url()
    if not resolved_db_url:
        return

    conn = psycopg2.connect(resolved_db_url) if db_url else connect_db()
    try:
        apply_schema_updates(conn)
    finally:
        conn.close()
