import os

import psycopg2

from api.db.connection import connect_db, get_database_url
from api.services.app_settings import bootstrap_settings_from_env, ensure_settings_schema

CANONICAL_FEEDBACK_VALUES = (
    "interested",
    "never_watch",
    "watched_like",
    "watched_dislike",
)


def apply_schema_updates(conn) -> None:
    with conn.cursor() as cur:
        ensure_settings_schema(conn)
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.feedback_reason (
                code text PRIMARY KEY,
                label text NOT NULL,
                applies_to text NOT NULL,
                suppress_default boolean NOT NULL DEFAULT false
            )
            """
        )
        cur.execute(
            """
            CREATE TABLE IF NOT EXISTS public.user_feedback (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username text NOT NULL,
                rating_key integer NOT NULL,
                feedback text NOT NULL,
                reason_code text REFERENCES public.feedback_reason(code),
                suppress boolean DEFAULT false,
                created_at timestamp without time zone DEFAULT now(),
                source text DEFAULT 'ui'
            )
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD COLUMN IF NOT EXISTS plex_watchlist_status text NOT NULL DEFAULT 'not_applicable'
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD COLUMN IF NOT EXISTS plex_watchlist_synced_at timestamp without time zone
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD COLUMN IF NOT EXISTS modified_at timestamp without time zone NOT NULL DEFAULT now()
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS label_source text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.training_data
            ADD COLUMN IF NOT EXISTS feedback_value text
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.library
            ADD COLUMN IF NOT EXISTS plex_guid text
            """
        )
        cur.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_library_plex_guid
            ON public.library (plex_guid)
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            DROP CONSTRAINT IF EXISTS user_feedback_feedback_check
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.feedback_reason
            DROP CONSTRAINT IF EXISTS feedback_reason_applies_to_check
            """
        )
        cur.execute(
            """
            UPDATE public.feedback_reason
            SET
                applies_to = CASE
                    WHEN code = 'thumb_up' THEN 'interested'
                    WHEN code = 'thumb_down' THEN 'never_watch'
                    ELSE applies_to
                END,
                suppress_default = CASE
                    WHEN code = 'thumb_up' THEN TRUE
                    WHEN code = 'thumb_down' THEN TRUE
                    ELSE suppress_default
                END
            WHERE code IN ('thumb_up', 'thumb_down')
            """
        )
        cur.execute(
            """
            INSERT INTO public.feedback_reason (code, label, applies_to, suppress_default)
            VALUES
                ('interested', 'Want to watch', 'interested', TRUE),
                ('never_watch', 'Never watch', 'never_watch', TRUE),
                ('watched_like', 'Watched, liked', 'watched_like', TRUE),
                ('watched_dislike', 'Watched, disliked', 'watched_dislike', TRUE)
            ON CONFLICT (code) DO UPDATE SET
                label = EXCLUDED.label,
                applies_to = EXCLUDED.applies_to,
                suppress_default = EXCLUDED.suppress_default
            """
        )

        cur.execute(
            """
            UPDATE public.user_feedback
            SET
                feedback = CASE
                    WHEN feedback = 'up' THEN 'interested'
                    WHEN feedback = 'down' THEN 'never_watch'
                    ELSE feedback
                END,
                reason_code = CASE
                    WHEN reason_code = 'thumb_up' THEN 'interested'
                    WHEN reason_code = 'thumb_down' THEN 'never_watch'
                    ELSE reason_code
                END,
                suppress = CASE
                    WHEN feedback = 'up' THEN TRUE
                    WHEN feedback = 'down' THEN TRUE
                    ELSE suppress
                END,
                plex_watchlist_status = CASE
                    WHEN feedback = 'up' AND COALESCE(plex_watchlist_status, '') IN ('', 'not_applicable')
                        THEN 'unresolved'
                    ELSE COALESCE(plex_watchlist_status, 'not_applicable')
                END,
                modified_at = COALESCE(modified_at, created_at, now())
            WHERE
                feedback IN ('up', 'down')
                OR reason_code IN ('thumb_up', 'thumb_down')
            """
        )
        cur.execute(
            """
            UPDATE public.user_feedback
            SET
                suppress = TRUE,
                plex_watchlist_status = CASE
                    WHEN feedback = 'interested'
                         AND COALESCE(plex_watchlist_status, '') IN ('', 'not_applicable')
                        THEN 'unresolved'
                    ELSE COALESCE(plex_watchlist_status, 'not_applicable')
                END,
                modified_at = COALESCE(modified_at, created_at, now())
            WHERE feedback = 'interested'
              AND suppress IS DISTINCT FROM TRUE
            """
        )

        cur.execute(
            """
            WITH ranked AS (
                SELECT
                    id,
                    ROW_NUMBER() OVER (
                        PARTITION BY username, rating_key
                        ORDER BY COALESCE(modified_at, created_at, now()) DESC, id DESC
                    ) AS rn
                FROM public.user_feedback
            )
            DELETE FROM public.user_feedback uf
            USING ranked
            WHERE uf.id = ranked.id
              AND ranked.rn > 1
            """
        )

        cur.execute(
            """
            ALTER TABLE IF EXISTS public.user_feedback
            ADD CONSTRAINT user_feedback_feedback_check
            CHECK (
                feedback = ANY (
                    ARRAY[
                        'interested'::text,
                        'never_watch'::text,
                        'watched_like'::text,
                        'watched_dislike'::text
                    ]
                )
            )
            """
        )
        cur.execute(
            """
            ALTER TABLE IF EXISTS public.feedback_reason
            ADD CONSTRAINT feedback_reason_applies_to_check
            CHECK (
                applies_to = ANY (
                    ARRAY[
                        'interested'::text,
                        'never_watch'::text,
                        'watched_like'::text,
                        'watched_dislike'::text
                    ]
                )
            )
            """
        )
        cur.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS idx_user_feedback_username_rating_key
            ON public.user_feedback (username, rating_key)
            """
        )
    conn.commit()
    bootstrap_settings_from_env(conn)


def ensure_app_schema(db_url: str | None = None) -> None:
    resolved_db_url = db_url or get_database_url()
    if not resolved_db_url:
        return

    conn = psycopg2.connect(resolved_db_url) if db_url else connect_db()
    try:
        apply_schema_updates(conn)
    finally:
        conn.close()
